#Language handling for message popups
#messageHandler -> MessageHandler.java
#

title.error=Kļūdas paziņojums
title.warning=Brīdinājuma paziņojums
title.info=Info paziņojums
title.success=Veiksmes paziņojums



#Language handling for message handling for logic generator
#logicalOperation -> LogicGenerator.java
#

message.error.variable_overflow=Nav iespējams izveidot, jo mainīgie > operāciju skaits + 1
message.error.variable_limit=Nav iespējams izveidot, jo mainīgo limits ir 52
message.error.variables_underflow=Nav iespējams izveidot, jo mainīgo daudzums nevar būt mazāks par 1
message.error.operations_underflow=Nav iespējams izveidot, jo operatoru daudzums nevar būt mazāks par 0
message.error.negations_underflow=Nav iespējams izveidot, jo negāciju daudzums nevar būt mazāks par 0
message.error.parenthesis_underflow=Nav iespējams izveidot, jo iekavu daudzums nevar būt mazāks par 0



#Language handling for error validation in LogicalCalculator
#logicalOperations -> LogicalCalculator.java
#

message.error.empty_input=Ievades lauks ir tukšs! Lūdzu, ievadiet izteiksmi.
error.validation.unmatched_brackets=Kļūda izteiksmē: neatbilstīgs vai nenoslēgts iekavu skaits!
error.validation.invalid_character=Izteiksme satur neatļautus simbolus vai nepareizu operatoru secību!


#Language handling for error handling for matrix generation
#matrix -> MatrixGenerator.java
#

message.error.invalid_dimensions=Matricas izmēri nevar būt mazāki par 1!
message.error.decimal_limit=Decimālzīmju skaits nevar pārsniegt 7 (float precizitātes limits)!



#Language handling for MatrixCalculator
#matrix -> MatrixCalculator.java
#

message.error.multiplication_mismatch=Matricas nevar sareizināt: pirmās matricas kolonnu skaitam jāsakrīt ar otrās matricas rindu skaitu!
message.error.dimensions_mismatch=Matricu izmēri nesakrīt: darbību var veikt tikai vienāda izmēra matricām!
message.error.not_square=Darbību nevar veikt: matricai ir jābūt kvadrātiskai (rindu skaitam jāvienojas ar kolonnu skaitu)!
message.error.singular_matrix=Matricas determinants ir 0, tāpēc inversā matrica neeksistē!
