#Language handling for message popups
#messageHandler -> MessageHandler.java
#

title.error=Kļūdas paziņojums
title.warning=Brīdinājuma paziņojums
title.info=Info paziņojums
title.success=Veiksmes paziņojums



#Language handling for message handling for logic generator
#logicalOperation -> LogicGenerator.java
#

message.error.variable_overflow=Nav iespējams izveidot, jo mainīgie > operāciju skaits + 1
message.error.variable_limit=Nav iespējams izveidot, jo mainīgo limits ir 52
message.error.variables_underflow=Nav iespējams izveidot, jo mainīgo daudzums nevar būt mazāks par 1
message.error.operations_underflow=Nav iespējams izveidot, jo operatoru daudzums nevar būt mazāks par 0
message.error.negations_underflow=Nav iespējams izveidot, jo negāciju daudzums nevar būt mazāks par 0
message.error.parenthesis_underflow=Nav iespējams izveidot, jo iekavu daudzums nevar būt mazāks par 0